# Generated by Django 5.0.1 on 2024-02-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginreg', '0002_invoice_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='all_total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=20, null=True),
        ),
    ]
