# Generated by Django 5.0.1 on 2024-02-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginreg', '0003_invoice_all_total_invoice_gst_rate_invoice_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
