# Generated by Django 5.0.1 on 2024-02-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginreg', '0004_invoice_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='remove',
            field=models.BooleanField(default=False),
        ),
    ]
