# Generated by Django 5.0.1 on 2024-02-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginreg', '0008_alter_historicalinvoice_amount_due_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
