# Generated by Django 5.0.1 on 2024-02-13 14:45

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginreg', '0009_historicalinvoice_email_invoice_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinvoice',
            name='address',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='address',
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='address_line1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='address_line2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='country',
            field=django_countries.fields.CountryField(default='IN', max_length=2),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='zip_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='address_line1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='address_line2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='country',
            field=django_countries.fields.CountryField(default='IN', max_length=2),
        ),
        migrations.AddField(
            model_name='invoice',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='zip_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
