# Generated by Django 5.0.1 on 2024-02-16 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginreg', '0011_historicalinvoice_gst_no_historicalinvoice_hsn_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='username',
            new_name='email',
        ),
    ]
