# Generated by Django 5.0.1 on 2024-02-18 13:02

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginreg', '0012_rename_username_admin_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('address_line1', models.CharField(max_length=200, null=True)),
                ('address_line2', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('zip_code', models.CharField(max_length=10, null=True)),
                ('country', django_countries.fields.CountryField(default='IN', max_length=2)),
                ('gst_no', models.CharField(max_length=50, null=True)),
                ('hsn_no', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
