# Generated by Django 5.0.1 on 2024-03-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginreg', '0014_customer_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='hsn_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalinvoice',
            name='hsn_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='hsn_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
